# Handling Reading
exclude: [README.md]

# Conversion
markdown: kramdown

# Serving
url:
  root:
  assets:
  blog:
  service:
  biogeek: 

# Outputting
permalink: /blog/:year/:month/:day/:title/
defaults:
  -
    scope:
      path: service/product
    values:
      layout: service
  -
    scope:
      path: service/solution
    values:
      layout: service
