# Handling Reading
exclude: [Gemfile, Gemfile.lock, README.md, Rakefile]

# Conversion
markdown: kramdown

# Serving
url:
  root:
  assets:
  blog:
  service:
  biogeek:

# Outputting
permalink: /blog/:year/:month/:day/:title/
